export const elements = {
  startButton: document.getElementById('start-button'),
  titleScreen: document.getElementById('title-screen'),
  gameContainer: document.getElementById('game-container'),
  loadingScreen: document.getElementById('loading-screen'),
  loadingPanel: document.querySelector('#loading-screen .loading-panel'),
  loadingProgressBar: document.getElementById('loading-progress'),
  loadingProgressFill: document.getElementById('loading-progress-fill'),
  loadingStatus: document.getElementById('loading-status'),
  optionsButton: document.getElementById('title-options-button'),
  inGameOptions: document.getElementById('in-game-options'),
  optionsScreen: document.getElementById('options-screen'),
  closeOptions: document.getElementById('close-options'),
  optionsForm: document.getElementById('options-form'),
  regenerate: document.getElementById('regenerate-button'),
  canvas: document.getElementById('world-canvas'),
  canvasWrapper: document.querySelector('.canvas-wrapper'),
  mapTooltip: document.getElementById('world-tooltip'),
  structureContextMenu: document.getElementById('structure-context-menu'),
  structureContextMenuBegin: document.getElementById('structure-context-menu-begin'),
  structureContextMenuMoreInfo: document.getElementById('structure-context-menu-more-info'),
  localMapPanel: document.getElementById('local-map-panel'),
  localMapCanvas: document.getElementById('local-map-canvas'),
  localMapTitle: document.getElementById('local-map-title'),
  localMapSubtitle: document.getElementById('local-map-subtitle'),
  localMapCoordinates: document.getElementById('local-map-coordinates'),
  localMapClose: document.getElementById('local-map-close'),
  localMapZoomIn: document.getElementById('local-map-zoom-in'),
  localMapZoomOut: document.getElementById('local-map-zoom-out'),
  localMapZoomReset: document.getElementById('local-map-zoom-reset'),
  localMapDetails: document.getElementById('local-map-details'),
  dwarfholdScreen: document.getElementById('dwarfhold-screen'),
  dwarfholdCanvas: document.getElementById('dwarfhold-canvas'),
  dwarfholdTitle: document.getElementById('dwarfhold-title'),
  dwarfholdSubtitle: document.getElementById('dwarfhold-subtitle'),
  dwarfholdDescription: document.getElementById('dwarfhold-description'),
  dwarfholdFeatures: document.getElementById('dwarfhold-features'),
  dwarfholdLegend: document.getElementById('dwarfhold-legend'),
  dwarfholdExit: document.getElementById('dwarfhold-exit'),
  dwarfholdCoordinates: document.getElementById('dwarfhold-coordinates'),
  structureDetailsPanel: document.getElementById('structure-details'),
  structureDetailsTitle: document.getElementById('structure-details-title'),
  structureDetailsSubtitle: document.getElementById('structure-details-subtitle'),
  structureDetailsContent: document.getElementById('structure-details-content'),
  structureDetailsTabs: Array.from(document.querySelectorAll('.structure-details-tab')),
  structureDetailsClose: document.getElementById('structure-details-close'),
  seedDisplay: document.querySelector('.seed-display'),
  politicalBordersToggle: document.getElementById('toggle-political-borders'),
  politicalInfluenceToggle: document.getElementById('toggle-political-influence'),
  elevationToggle: document.getElementById('toggle-elevation'),
  biomeToggle: document.getElementById('toggle-biomes'),
  temperatureToggle: document.getElementById('toggle-temperature'),
  locationLabelToggle: document.getElementById('toggle-location-labels'),
  structureHighlightToggle: document.getElementById('toggle-structure-highlights'),
  structureHighlightMenu: document.getElementById('structure-highlight-menu'),
  mapEditorToggle: document.getElementById('toggle-map-editor'),
  mapEditorPanel: document.getElementById('map-editor'),
  mapEditorClose: document.getElementById('map-editor-close'),
  mapEditorTerrainInput: document.getElementById('map-editor-terrain'),
  mapEditorStructureInput: document.getElementById('map-editor-structure'),
  mapEditorApplyTerrain: document.getElementById('map-editor-apply-terrain'),
  mapEditorApplyStructure: document.getElementById('map-editor-apply-structure'),
  mapEditorBrushSizeInput: document.getElementById('map-editor-brush-size'),
  mapEditorClearStructure: document.getElementById('map-editor-clear-structure'),
  mapEditorTerrainOptions: document.getElementById('map-editor-terrain-options'),
  mapEditorStructureOptions: document.getElementById('map-editor-structure-options'),
  mapSizeSelect: document.getElementById('map-size'),
  worldGenerationTypeSelect: document.getElementById('world-generation-type'),
  seedInput: document.getElementById('world-seed'),
  worldMapSizeSelect: document.getElementById('world-map-size-select'),
  worldSeedInput: document.getElementById('world-seed-input'),
  forestFrequencyInput: document.getElementById('forest-frequency'),
  forestFrequencyValue: document.getElementById('forest-frequency-value'),
  mountainFrequencyInput: document.getElementById('mountain-frequency'),
  mountainFrequencyValue: document.getElementById('mountain-frequency-value'),
  riverFrequencyInput: document.getElementById('river-frequency'),
  riverFrequencyValue: document.getElementById('river-frequency-value'),
  humanSettlementFrequencyInput: document.getElementById('human-settlement-frequency'),
  humanSettlementFrequencyValue: document.getElementById('human-settlement-frequency-value'),
  dwarfSettlementFrequencyInput: document.getElementById('dwarf-settlement-frequency'),
  dwarfSettlementFrequencyValue: document.getElementById('dwarf-settlement-frequency-value'),
  woodElfSettlementFrequencyInput: document.getElementById('wood-elf-settlement-frequency'),
  woodElfSettlementFrequencyValue: document.getElementById('wood-elf-settlement-frequency-value'),
  lizardmenSettlementFrequencyInput: document.getElementById('lizardmen-settlement-frequency'),
  lizardmenSettlementFrequencyValue: document.getElementById('lizardmen-settlement-frequency-value'),
  musicToggle: document.getElementById('music-toggle'),
  musicVolume: document.getElementById('music-volume'),
  musicNowPlaying: document.getElementById('music-now-playing'),
  musicToggleGame: document.getElementById('music-toggle-game'),
  musicVolumeGame: document.getElementById('music-volume-game'),
  musicNowPlayingGame: document.getElementById('music-now-playing-game'),
  sfxToggle: document.getElementById('sfx-toggle'),
  sfxVolume: document.getElementById('sfx-volume'),
  audioElement: document.getElementById('background-music'),
  structureAmbienceAudio: document.getElementById('structure-ambience'),
  worldInfoModal: document.getElementById('world-info'),
  worldInfoForm: document.getElementById('world-info-form'),
  worldInfoSize: document.getElementById('world-info-size'),
  worldInfoGenerationType: document.getElementById('world-info-generation-type'),
  worldInfoSeed: document.getElementById('world-info-seed'),
  worldInfoChronology: document.getElementById('world-info-chronology'),
  worldYearInput: document.getElementById('world-year-input'),
  worldAgeInput: document.getElementById('world-age-input'),
  worldChronologyRandom: document.getElementById('world-chronology-random'),
  worldInfoGenerationTypeSelect: document.getElementById('world-generation-type-select'),
  worldNameInput: document.getElementById('world-name-input'),
  worldNameRandom: document.getElementById('world-name-random'),
  worldInfoCancel: document.getElementById('world-info-cancel'),
  dwarfCustomizer: document.getElementById('dwarf-customizer'),
  dwarfCustomizerForm: document.getElementById('dwarf-customizer-form'),
  dwarfRosterList: document.getElementById('dwarf-roster-list'),
  dwarfPrev: document.getElementById('dwarf-prev'),
  dwarfNext: document.getElementById('dwarf-next'),
  dwarfSlotLabel: document.getElementById('dwarf-slot-label'),
  dwarfNameInput: document.getElementById('dwarf-name-input'),
  dwarfGenderButtons: document.getElementById('dwarf-gender-buttons'),
  dwarfClanSelect: document.getElementById('dwarf-clan-select'),
  dwarfProfessionSelect: document.getElementById('dwarf-profession-select'),
  dwarfSkinSlider: document.getElementById('dwarf-skin-slider'),
  dwarfSkinSliderValue: document.getElementById('dwarf-skin-slider-value'),
  dwarfEyeSlider: document.getElementById('dwarf-eye-slider'),
  dwarfEyeSliderValue: document.getElementById('dwarf-eye-slider-value'),
  dwarfHairStyleSlider: document.getElementById('dwarf-hair-style-slider'),
  dwarfHairStyleSliderValue: document.getElementById('dwarf-hair-style-slider-value'),
  dwarfHairSlider: document.getElementById('dwarf-hair-slider'),
  dwarfHairSliderValue: document.getElementById('dwarf-hair-slider-value'),
  dwarfBeardSlider: document.getElementById('dwarf-beard-slider'),
  dwarfBeardSliderValue: document.getElementById('dwarf-beard-slider-value'),
  dwarfBeardFieldGroup: document.getElementById('dwarf-beard-field-group'),
  dwarfRandomise: document.getElementById('dwarf-randomise'),
  dwarfBack: document.getElementById('dwarf-back'),
  dwarfPortrait: document.getElementById('dwarf-portrait'),
  dwarfPortraitCanvas: document.getElementById('dwarf-portrait-canvas'),
  dwarfBodyPortraitCanvas: document.getElementById('dwarf-body-portrait-canvas'),
  dwarfTestArea: document.getElementById('dwarf-test-area'),
  dwarfTestCanvas: document.getElementById('dwarf-test-canvas'),
  dwarfTestButton: document.getElementById('dwarf-test'),
  dwarfTestDungeonButton: document.getElementById('dwarf-test-dungeon'),
  dwarfTraitSummary: document.getElementById('dwarf-trait-summary'),
  dwarfTraitAttributes: document.getElementById('dwarf-trait-attributes')
};

export function getMusicToggleElements() {
  return [elements.musicToggle, elements.musicToggleGame].filter(Boolean);
}

export function getMusicVolumeInputs() {
  return [elements.musicVolume, elements.musicVolumeGame].filter(Boolean);
}

export function getMusicNowPlayingDisplays() {
  return [elements.musicNowPlaying, elements.musicNowPlayingGame].filter(Boolean);
}
